---
name: Parse-PhoneNumber
version: 1.5
author:
  - Casey West <F<casey@geeknest.com>>
abstract: Parse Phone Numbers
license: perl
build_requires:
  Module::Build: 0
  Test::More: 0
provides:
  Parse::PhoneNumber:
    file: lib/Parse/PhoneNumber.pm
    version: 1.5
  Parse::PhoneNumber::Number:
    file: lib/Parse/PhoneNumber.pm
    version: 1.5
generated_by: Module::Build version 0.25
